### ISSUE TITLE
Responsive navigation menu

### ISSUE THREAD

**Issue by guylepage3** [guylepage3/m3#104]
> **Last updated**: May 7, 2023

**Description**
As a result of moving framework and client to Next.js 13, you need to live design and build a new responsive navigation so that navigation is functional across all devices.

**Tasks**
- [x] Review and research responsive navigations for Next.js 13.4.
- [ ] Create new `nav` branch.
- [ ] Create process for navbar.
- [ ] Build responsive navigation.
- [ ] Test.
- [ ] Update version number in `package.json` and deploy app.
- [ ] Merge `nav` branch into `master`.

**Example menus**
- [CodePen — guylepage3 — Navigation](https://codepen.io/collection/PYaNWx).
- [Pure CSS3 Menu FullScreen](https://codepen.io/paulocesarpcfj/pen/mJgoez).

**Process**
- [ ] Research CodePen for vanilla JavaScript navigation menus.
- [ ] Research and find examples of how best to implement a responsive navigation in Next.js 13.4.
- [ ] Build working Next.js 13.4 responsive navigation menu.
- [ ] Configure responsive navigation menu to have 

**Tag(s)**
`hamburger` `hamburger menu` `nav` `navbar` `navigation` `menu`

**Reference(s)**
- [Cool CSS Hamburger Menu Icons and Their Animations](https://www.sliderrevolution.com/resources/css-hamburger-menu/).

**Comment by guylepage3** [comment]
**Architecture(s)**

**Bootstrap method**
All in one `div`

**JavaScript method**
- Two `div`'s;
  - Desktop
  - Mobile

**Comment by guylepage3** [comment]
**`useState()`**
